### ISSUE TITLE
correction options

### ISSUE THREAD

**Issue by bdarcus** [minad/jinx#1]
Hi @minad!

As usual, nice work on this!

Do I need to configure something to get more, and more useful, correction options?

![image](https://user-images.githubusercontent.com/1134/227809418-5b6e462c-1960-4e69-b06c-578bc522dbe1.png)

This is a minor variation on your example in the README screenshot, and I think should show "checking" as an option. But these are all I get, and I can't complete on any more than the four.

If I run enchant from command line, interestingly, it also doesn't give me what I'm looking for, though does give me more (7) other options.

```console
❯ enchant -a /tmp/test.txt
@(#) International Ispell Version 3.1.20 (but really Enchant 1.6.0)
& chking 7 0: choking, caking, coking, ch king, ch-king, chinking, chinning
```

**Comment by minad** [comment]
Thanks for trying Jinx early!

Note that you can just input the word "Checking", you don't have to use any of the completion candidates.

This is really an issue of the backend. In my setup I also use Hunspell as a backend, I also don't get the word "Checking", but I do get the 7 options both on the command line and via completion. 

Not sure what is wrong and why you only get 4 suggestions displayed. Your Enchant package seems very old, so that could be a problem. I have Enchant 2.2.15 on my system. Do you have a chance to update it or are you forced to use a ridiculously outdated Linux distribution?

**Comment by bdarcus** [comment]
I see the problem.

I'm on Fedora, which is actually really good on being up-to-date in general.

I have both the `enchant` and (now) `enchant2` packages installed, with the latter providing the `enchant-2` command. 
I and jinx were obviously using the former.

Obviously I can remove the old one; will jinx pick up `enchant-2`?

**Comment by minad** [comment]
You can probably also configure Enchant to use a different backend or to provide more suggestions. Aspell seems to provide more suggestions, but I believe it is less advanced overall.

I have to figure out how to do such configuration, but it seems one needs to either use environment variables or configuration files. For example I have a file /usr/share/enchant-2/enchant.ordering on my system, which configures which backend to use:

~~~ elisp
*:hunspell,nuspell,aspell
fi:voikko,hunspell,nuspell,aspell
fi_FI:voikko,hunspell,nuspell,aspell
he:hspell,hunspell,nuspell
he_IL:hspell,hunspell,nuspell
tr:zemberek,nuspell
tr_TR:zemberek,nuspell
~~~

**Comment by bdarcus** [comment]
OK, thanks.

I'm seeing somewhat weird behavior now.

Initially, when I removed `enchant`, `jinx` was giving me the same options the command line was, including "checking."

Now, after restarting, it's giving me what I first reported, which of course differs from what I see on the command line.

Any ideas on that?

**Comment by alphapapa** [comment]
@bdarcus Since Jinx compiles and loads an Emacs module, I would guess that you'd need to recompile the module for the new version of Enchant.

**Comment by bdarcus** [comment]
> @bdarcus Since Jinx compiles and loads an Emacs module, I would guess that you'd need to recompile the module for the new version of Enchant.

That's not it, it turns out.

I reinstalled and `jinx` recompiled the module, and I still get the same results.

**Comment by alphapapa** [comment]
@bdarcus Just to be sure, did you ensure that the old compiled module file was deleted, and did you restart Emacs after deleting the old module?  

Also, you might want to ensure that old library headers or dev packages aren't still installed.  I don't use Fedora, so I'm not sure how it handles that, but e.g. on Debian/Ubuntu, there's the package `libenchant-2-dev` which provides the headers against which the Jinx module would be compiled; so if an old version of such a package were still installed, maybe it could be used by accident when the module is built?

**Comment by minad** [comment]
@alphapapa I have my doubts that libenchant-1 was the problem here, since jinx-mod.c wouldn't compile against that. Note that jinx--load-module explicitly triggers the linker with `-lenchant-2`. Now it could have happened that the enchant.h header from enchant-1 was used which then lead to a binary incompatibility. I will check the enchant.h header from enchant-1 to make sure that this cannot happen.

**Comment by bdarcus** [comment]
Just to clarify a bit more, when I say I reinstalled jinx, I mean I deleted the repo and the build directory, and then reinstalled.

I'm using elpaca for managing the installs.

I seriously doubt dnf leaves files around that it says it deletes, but I'll see if I can find anything when I find time.

Regardless, ideally, the module shouldn't ever build against the wrong version, which I guess is what @minad is saying?

**Comment by mavit** [comment]
> You can probably also configure Enchant to use a different backend or to provide more suggestions. Aspell seems to provide more suggestions, but I believe it is less advanced overall.

[Aspell is the default for English](https://github.com/AbiWord/enchant/pull/271) for recent versions of Enchant (which is what you'll have on Fedora).

> I have to figure out how to do such configuration,

See https://abiword.github.io/enchant/src/enchant.html#ORDERING%20FILE

**Comment by minad** [comment]
@bdarcus Any news on this? Does anybody else observe such issues with Jinx?

**Comment by bdarcus** [comment]
Oh sorry; it does work now as expected now.
