### ISSUE TITLE
Should Jinx export all symbols by default?

### ISSUE THREAD

**Issue by Thaodan** [minad/jinx#105]
Similar to other Emacs module Jinx does export all it's symbols.
Some modules such as vterm or zmq changed to only export neccessary symbols such as `plugin_is_GPL_compatible` and `emacs_module_init`.

Refs:
https://github.com/akermu/emacs-libvterm/pull/562
https://github.com/nnicandro/emacs-zmq/pull/36

**Comment by minad** [comment]
Thanks. Are you sure that this change is necessary? We have only a single compilation unit with all functions marked as `static` the only globally exported symbols are `emacs_module_init` and `plugin_is_GPL_compatible`. The distinction of exported and non-exported symbols is relevant when we have multiple compilation units.

**Comment by Thaodan** [comment]
Vterm is also one only object/compilation unit and had this issue which
caused Emacs to crash:
https://github.com/akermu/emacs-libvterm/issues/559

I think even if it's not 100% needed it's just good practice to not
export symbols which shouldn't be public.
One such as examples from the bug where Qt and Qnil.

The first comment on the very similar PR on ZMQ explained the issue
quite good.

**Comment by minad** [comment]
> Vterm is also one only object/compilation unit

Doesn't look like that to me. Multiple C files in https://github.com/akermu/emacs-libvterm.

> I think even if it's not 100% needed it's just good practice to not
export symbols which shouldn't be public.

My claim is that jinx-mod.so doesn't export any such symbols right now. I checked with `-fvisibility=hidden` and there wasn't any difference.

**Comment by minad** [comment]
Okay, I close this one as long it is not clear that we have a problem.
