### ISSUE TITLE
Add workaround for deadlock on `railwaycat` emacs mac as a temporary workaround in the readme. 

### ISSUE THREAD

**Issue by appetrosyan** [minad/jinx#113]
It's considered a good idea to have some troubleshooting steps available in case people don't know what's wrong. 

Given that there's a known bug with no upstream fix, I believe it would be helpful to post something along the lines of *known issues* with a known workaround. 

```lisp
(use-package jinx
  :defer t
  :config
  (jinx--load-module)
  (make-thread #'(lambda()(jinx--mod-dict "any-lang") "my/jinx-init"))
  :hook (emacs-startup . global-jinx-mode)
  :bind (("M-$" . jinx-correct)
         ("C-M-$" . jinx-languages)))
```

Just correcting the `use-package` definition is IMO the best solution as it prevents issues. 

This workaround is not universal (doesn't work for me) so a message along the lines of 

> The `jinx` package has been reported to misbehave on some ports of emacs on Mac OS X Apple Silicon. If you experience a hard lockup of the UI, consider disabling the `jinx` package. 

would also be helpful, especially if it's at the top of the README.

**Comment by minad** [comment]
I don't know which versions are affected exactly. I am not even familiar with the different unofficial ports. The problem is also not related to apple silicon as far as I understood. I would accept a PR which lists the affected versions/ports, but I cannot investigate this myself.

**Comment by jdtsmith** [comment]
Finally got around to trying jinx and encountered this lockup (but not on first installation, only on an emacs restart).  This workaround works for me.   

For your edification, there are only two "flavors" of emacs ports on MacOS: NS (current official port) and Carbon (officially distributed until Emacs 22).  All other "versions" you may have heard of are based on the NS port.  There is only one Carbon port: [emacs-mac](https://bitbucket.org/mituharu/emacs-mac/src/master/README-mac).  "railwaycat" is just a user who bundled emacs-mac for the `brew` package manager, so some people call it that.  All other MacOS version are just NS in disguise.  

@appetrosyan, did someone report this bug to the emacs-mac maintainer?

**Comment by appetrosyan** [comment]
I think they did, and it was closed. Basically they said “it’s a package problem”

**Comment by appetrosyan** [comment]
I'll try and see if I can fix it by using a more recent version.

**Comment by jeff-phil** [comment]
@appetrosyan New fix was put in from discussion in https://github.com/minad/jinx/pull/91 if want details.
