### ISSUE TITLE
Feature Request: support switching languages

### ISSUE THREAD

**Issue by bymoz089** [minad/jinx#13]
While this feature request is simple to implement on init.el level, maybe it could be a nice addition to jinx. 

The idea from user perspective is:         
A user which normally works on multiple languages say "de" and "en" and has both enabled per default, could then easily switch to another language mode. Lets say he is learning french at school and often needs to write french texts. other use cases are imaginable.

Possible implementation:              
To be able to manage multiple languages the variable `jinx-languages`, would be a list of lists of languages. And a command lets say `jinx-next-language-config`, which creates a buffer-local variable e.g. `current-jinx-languages`. The command then switches to the next language list of `jinx-languages` and restarts `jinx-mode` for this buffer.

**Comment by minad** [comment]
There is one other argument in favor of this. The backend libenchant offers an API to retrieve all the dictionaries. Would be nice to see which dictionaries are installed and then select from them.

**Comment by bymoz089** [comment]
This introduced some bug.
If `global-jinx-mode` is enabled and the user opens a file (or reverts a buffer) with unknown unsafe file local variables. following error is displayed:

    File local-variables error: (no-catch exit Command attempted to use minibuffer while in minibuffer)


Debugger shows following:

    Debugger entered--Lisp error: (no-catch exit "Command attempted to use minibuffer while in minib...")
    read-char-from-minibuffer("Please type y, n, ! or i, or C-v/M-v to scroll: " (33 105 121 110 32))
    read-char-choice("Please type y, n, ! or i, or C-v/M-v to scroll: " (33 105 121 110 32))
    hack-local-variables-confirm(((baz . t)) ((baz . t)) nil nil)
    hack-local-variables-filter(((baz . t)) nil)
    hack-local-variables()
    jinx-mode(1)
    jinx--on()
    global-jinx-mode-enable-in-buffers()
    run-hooks(after-change-major-mode-hook)
    run-mode-hooks(minibuffer-mode-hook)
    minibuffer-mode()
    read-char-from-minibuffer("Please type y, n, ! or i, or C-v/M-v to scroll: " (33 105 121 110 32))
    read-char-choice("Please type y, n, ! or i, or C-v/M-v to scroll: " (33 105 121 110 32))
    hack-local-variables-confirm(((baz . t)) ((baz . t)) nil nil)
    hack-local-variables-filter(((baz . t)) nil)
    hack-local-variables(no-mode)
    run-mode-hooks(text-mode-hook)
    text-mode()
    set-auto-mode-0(text-mode nil)
    set-auto-mode--apply-alist(--long-list-cut-out-- nil nil)
    set-auto-mode()
    normal-mode(t)
    after-find-file(nil t)
    find-file-noselect-1(#<buffer moo.txt> "moo.txt" nil nil "moo.txt" (30 33))
    find-file-noselect("moo.txt" nil nil t)
    find-file("moo.txt" t)
    funcall-interactively(find-file "moo.txt" t)

So, jinx calls `hack-local-variables` a second time, and this should not happen if `global-jinx-mode` is active and a file is opened or reverted.

This has been verified with `emacs -Q` (multiple times :-) ).         
When using my own init.el, I can see a second (recursive) prompt, which asks for allowance of file local vars, on loading or reverting such a file.

**Comment by bymoz089** [comment]
yes, that fixed it.
