### ISSUE TITLE
Jinx is behind Enchant

### ISSUE THREAD

**Issue by summeremacs** [minad/jinx#134]
Hi Minad,
I had to manually fix my Jinx/Enchant because Jinx is behind Enchant by 2 versions.
OS: MacOS
Brew installs enchant 2.6.7 but Jinx was looking for 2.6.5. I figured out how to downgrade my enchant to fix it (it works now! Yay!).
I just wanted to leave you a note so you know.
🙃

**Comment by minad** [comment]
Jinx will use the Enchant version provided by pkgconf during compilation of the Emacs module. Reinstalling Jinx should fix this.

**Comment by summeremacs** [comment]
Sorry to contrary you 🙃, but neither reinstalling Jinx, pkgconf, or enchant from scratch solve it. Neither did completely uninstalling, wiping everything clean with brew cleanup, or anything else solve it. The only thing which solved it was installing enchant 2.6.5. Believe me, I tried uninstalling everything, updating, and reinstalling everything from scratch. It didn't work. 😐

**Comment by minad** [comment]
Oh, that's unfortunate. It could be that there is a bug in the pkgconf description, some version specified incorrectly? Jinx nowhere encodes a fixed version of Enchant. It just takes what it gets from pkgconf.

**Comment by summeremacs** [comment]
Ok, I guess that's where the issue is then. I don't know nearly enough to know any of that or how to detail it in a bug report. 🙃 I just wanted to let you know about it.

**Comment by minad** [comment]
We can narrow this down a little. The problem does not seem to be in libenchant, when I compare the two version bumps, where nothing else than the version has been changed:

* [2.6.5](https://github.com/AbiWord/enchant/commit/7aa290d8c8933043d0b28d411754dd541c608281)
* [2.6.7](https://github.com/AbiWord/enchant/commit/8de88dad34841f578caff4e35adef03883609e9b)

Here is the Homebrew history for enchant: https://github.com/Homebrew/homebrew-core/commits/8e83c974094cbcc52c8a8e5154de9191eac28bab/Formula/e/enchant.rb. I don't see anything obviously wrong. I don't know either where the problem lies. Maybe something went wrong during the update from 2.6.5 to 2.6.7. But I guess you tried all this, reinstalling Enchant (various versions) and reinstalling Jinx.

**Comment by summeremacs** [comment]
Yea, I tried everything, including removing the directories entirely, cleanup, and relinking just to make sure there was nothing left.

Also, I noticed that I had to run the gcc command in ~/.emacs.d/straight/repos/jinx or it wouldn't find jinx-mod.dylib.

**Comment by minad** [comment]
> Also, I noticed that I had to run the gcc command in ~/.emacs.d/straight/repos/jinx or it wouldn't find jinx-mod.dylib.

This does not sound right. Jinx should automatically compile the Emacs module for you. I don't have a Mac so I cannot check myself.

I know that @jdtsmith recently started to use Jinx on Mac - I assume with Homebrew. JD, can you please give Enchant 2.6.7 a quick check? Have you seen similar Enchant upgrade issues before?

**Comment by summeremacs** [comment]
Then I honestly don't know what it is. I didn't have a problem before and I only do the usual brew update && brew upgrade, so nothing special there. I wish I knew more to be able to find out what went wrong, but at least I know how to install a previous version from brew now. 🙃

**Comment by jdtsmith** [comment]
I haven't had any problems, but I have been on `enchant: stable 2.6.5 (bottled)`.   

I just upgraded to enchant 2.6.7 (using brew) and jinx 1.2 without incident. It automatically recompiled and loaded `jinx-mod.dylib`. I don't see that jinx has a hard dependency on any version of enchant (as long as it's >=2.3.1).

**Comment by summeremacs** [comment]
Okay, well something is wrong on my end then? Because it works with 2.6.5 but when I upgraded earlier, it couldn't compile, or find any paths. Maybe my zsh path lines are incorrect? I'll publish them here so you can check if that's the problem? I'm sorry for all of this confusion:
(This is why emacs and *nix is not ready for newbies btw....)

`# Enchant/Jinx
export LIBRARY_PATH="/opt/homebrew/opt/enchant/lib/:$LIBRARY_PATH"
#export LIBRARY_PATH="/opt/homebrew/Cellar/enchant/2.6.7/lib/:$LIBRARY_PATH"
#export C_INCLUDE_PATH="/opt/homebrew/Cellar/enchant/2.6.7/include/enchant-2a:$C_INCLUDE_PATH"
export LIBRARY_PATH="/opt/homebrew/Cellar/enchant/2.6.5/lib/:$LIBRARY_PATH"
export C_INCLUDE_PATH="/opt/homebrew/Cellar/enchant/2.6.5/include/enchant-2a:$C_INCLUDE_PATH"
export C_INCLUDE_PATH="/Users/summer/.emacs.d/straight/repos/jinx:$C_INCLUDE_PATH"
export LIBRARY_PATH="/Users/summer/.emacs.d/straight/repos/jinx:$LIBRARY_PATH"
export LIBRARY_PATH="/opt/homebrew/Cellar/enchant:$LIBRARY_PATH"
export C_INCLUDE_PATH="/opt/homebrew/Cellar/enchant/:$C_INCLUDE_PATH"
`
I realise it's probably more than I need, but I wanted to be sure. Please let me know (I know that 2.6.7 is commented out, that's just a recent thing. IT wasn't commented out when I tried compiling with 2.6.7)

**Comment by jdtsmith** [comment]
I didn't need to use any of these env-vars.

**Comment by summeremacs** [comment]
> I didn't need to use any of these env-vars.

It wouldn't work without it.

**Comment by jdtsmith** [comment]
Not sure what the issue is for you, I'd start all over, remove jinx, remove enchant, and just a simple `brew install enchant` and `package-install jinx` should do the trick.

**Comment by minad** [comment]
@jdtsmith Thank you for your help here. As you wrote, not much intervention by the user should be necessary if the required package are around, no environment variables etc. Locating enchant is the responsibility of pkgconfig or pkgconf.
