### ISSUE TITLE
Check only visible text

### ISSUE THREAD

**Issue by walseb** [minad/jinx#143]
Currently, commands like `jinx-correct-all`, and `jinx-correct-nearest` tries to correct words that aren't visible (for instance those folded with folding tools, or outline-mode).

While thorough, sometimes, this isn't useful. For instance today, I folded headings containing massive amounts of text in an attempt to exclude them from being spell checked when checking other text.

I could have achieved the same thing by narrowing a bunch of times and spell checking those individual buffers, but that would have taken a long time and be error prone. I ended up just patching Jinx to only check visible text.

Would you be open to a patch that adds a variable `jinx-check-only-visible` to change this behavior?

**Comment by minad** [comment]
Yes, please submit the patch. Jinx usually only updates unfolded regions lazily, but `jinx-correct-all` and `jinx-correct-nearest` enforce spell checking in the whole region, and does not take folded regions into account. Did you also change that?
