### ISSUE TITLE
Respect face inheritance?

### ISSUE THREAD

**Issue by DamienCassou** [minad/jinx#147]
Hi,

`js2-mode` which indirectly derives from `prog-mode` defines a face `js2-jsdoc-value` that modus-theme makes inherit from `font-lock-comment-face` (see below for the complete definition).

Because `jinx-include-faces` specifies that `font-lock-comment-face` of `prog-mode` should be included, I would expect that `js2-jsdoc-value` to be included in jinx analyses. But it's not: `jinx--face-ignored-p` searches faces ignoring inheritance.

```
           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: normal
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: (font-lock-constant-face font-lock-comment-face)
```

**Comment by minad** [comment]
Hi, traversing the face inheritance hierarchy is not currently done in Jinx since I suspect that it will be less efficient. Also it may lead to false positives. You can add the respective face explicitly to the face exclusion list.

**Comment by DamienCassou** [comment]
> You can add the respective face explicitly to the face exclusion list

I think you meant "inclusion" list instead. That's what I'm currently doing.

> it may lead to false positives

good point.

> I suspect that it will be less efficient

most probably yes. If one day you change your mind and you want to do it anyway it could be possible to make it fast by caching the result of the inheritance lookup into `jinx--include-faces` (if the lookup found a matching face) or `jinx--exclude-faces` otherwise. This way, the lookup is only done once per face: this should make the algorithm face if the buffer doesn't use too many different faces.
