### ISSUE TITLE
Multi language document, but with parts of buffer being spell checked by different dictionaries

### ISSUE THREAD

**Issue by gusbrs** [minad/jinx#15]
This is more of a question really and, depending on the answer, may become a suggestion. (Disclaimer: I haven't tested it yet).

The question is: Since `jinx` is made completely independent of `ispell`, and comunicates to `libenchant` directly, does the way it relates to `libenchant` makes it possible to spell check a multi language document by sending the document piecewise to different dictionaries, according to the language of the current part, instead of using multiple dictionaries for the whole buffer?

Let's say, for the sake of argument, that we have a buffer where different parts carry a text property specifying its spell check language. Some languages, e.g. LaTeX, have a language markup from which such text property could be set automatically. With something of the sort in hand, would it be possible to spell check each part with it's own dictionary?

For context, as far as I'm aware, there are some alternatives for multi language documents. I think the most common one is the use of multiple dictionaries for the whole buffer. That's what `ispell-hunspell-add-multi-dic` does and, as far as I can tell, that's also what `jinx` does. It is simple and effective, but the drawback is also clear: if at a given point you are writing in language A, but commits a typo which happens to exist in language B, it won't be flagged as a mistake.

Another approach to the problem is trying to guess the language by the content of the buffer (common words, etc.). `guess-language` (https://github.com/tmalsburg/guess-language.el) is one such example. I recall having tested it at some point and, if I remember correctly, it tried to guess the language for each paragraph, and changed the buffer dictionary according to where point was. I thought the constant change of dictionary a bit jarring, or perhaps I never got used to it.

Yet another approach (which is more or less what I have in mind with this question) is to partition the buffer, and check each part with an individual dictionary. It is easy to see the advantages of this, but it is obviously more complex. I recall seeing a package in my early Emacs days which did something of the sort, I think at the time I "found it around", EmacsWiki perhaps. I'm not sure, but I believe it is `ispell-multi.el` (https://github.com/pjheslin/flyspell-multilingual). I don't think this has made to any package repo and the readme says it is not being kept up to date. (This thread may also be of interest: https://lists.gnu.org/archive/html/emacs-devel/2007-06/msg00840.html, I haven't read it through tough). If I remember correctly, and the readme seems to confirm, this was done by keeping one ispell process for each language at play.

**Comment by minad** [comment]
Yes, it is no problem to implement this since we already load multiple dictionaries. We can restrict the dictionaries to regions. I have already thought about this. We can introduce a `jinx-dictionary-function` which returns the list of dictionaries given a region. This function should then be called by `jinx--check-region`. However I consider this an advanced feature and it is not needed for now. I have to gather more feedback first on basic functionality. We can revisit this in a year.

**Comment by gusbrs** [comment]
> Yes, it is no problem to implement this since we already load multiple dictionaries. We can restrict the dictionaries to regions. I have already thought about this. We can introduce a `jinx-dictionary-function` which returns the list of dictionaries given a region. This function should then be called by `jinx--check-region`.

> We can revisit this in a few months or a year. It may happen that I feel the need for this functionality earlier, but it is not likely.

Ok, thanks for considering, and I'll be happy if you keep the possibility in mind. And good to know it is possible in principle.

> The main problem as you already wrote is to detect the regions. I don't want to glue Jinx to guess-language. One could maybe provide a dictionary function which handles some common cases.

Yeah, I also don't think guess-language is the way to go for this. As I said, some languages already carry the information. LaTeX does, it would not be too complicated to infer the language from `babel` and `polyglossia` markup. So it'd be viable to have such text property applied to the text. Of course, other languages do not, e.g. Org. I can conceive a "markup in comments" to signal the language, but it is not a pretty idea... Anyway, (at least) where the information is readily available, it would be a valuable possibility.

> I consider this an advanced feature and it is not needed for now. I have to gather more feedback first on basic functionality.

Well, you asked for early feedback.  ;-)  And I thought of this as something which would be harder to include at a later, more mature, stage. But I do get your point. So, understood. And thanks!

**Comment by minad** [comment]
Thanks! Yes, I asked for early feedback. I appreciate the proposal and I had already considered this. Right now it is just more important that the basics work well enough. It will be possible to add this later.

> LaTeX does, it would not be too complicated to infer the language from babel and polyglossia markup. 

This would be good to support. One could have a dictionary function which detects the language relevant for the given region.

> Of course, other languages do not, e.g. Org. 

Are you sure? This sounds like a missing feature in Org then. Is it not possible to specify language per headline? On the other hand Org doesn't really benefit much from knowing about the current language. We could support a special headline language property.

> Anyway, (at least) where the information is readily available, it would be a valuable possibility.

Yes, but the examples given so far are quite limited. There is basically only TeX, xml:lang and maybe Org or Markdown with some additional annotations. Multi language documents are just not that common in general, maybe in specific academic fields, history, linguistics etc.

**Comment by gusbrs** [comment]
> Thanks! Yes, I asked for early feedback. I appreciate the proposal and I had already considered this. Right now it is just more important that the basics work well enough. It will be possible to add this later.

Understood. And thank **you**!

> This would be good to support. One could have a dictionary function which detects the language relevant for the given region.

It would be great...

> Are you sure? This sounds like a missing feature in Org then. Is it not possible to specify language per headline? On the other hand Org doesn't really benefit much from knowing about the current language. We could support a special headline language property.

Actually, I'm not sure. But I don't recall having used this in Org. I know you can specify the language for the document as an option. I don't know if it  can be set for a headline. I'd be surprised if one can set it for an environment, e.g. a quote. And I doubt there's a way to do so for an arbitrary piece of text. Anyway, if there is, better.

> Yes, but the examples given so far are quite limited. There is basically only TeX, xml:lang and maybe Org or Markdown with some additional annotations. Multi language documents are just not that common in general, maybe in specific academic fields, history, linguistics etc.

You may say "limited", I'd say ok, but "relevant ones", at least. Besides, personally, for me the most common case for a formal document is to have more than one language (and I'm even frequently bitten by variants of my own native language, old spelling and such). And I think it is fair to say that, at least to some extent independent of field/area, for those who are not from English speaking countries, a multi language document is a common need.

Furthermore, if the API exists, I'd bet people will find their ways, as they always do.

**Comment by minad** [comment]
> And I think it is fair to say that, at least to some extent independent of field/area, for those who are not from English speaking countries, a multi language document is a common need.

My notes are often mix of German and English for example. However I am happy with just enabling both dictionaries then. :shrug:

**Comment by gusbrs** [comment]
> My notes are often mix of German and English for example. However I am happy with just enabling both dictionaries then. shrug

That's what I do too. In part, because that's what's possible. In part, it is indeed enough for personal notes. For a formal document aimed for publication, I'm less happy to do so.

**Comment by doolio** [comment]
> My notes are often mix of German and English for example. However I am happy with just enabling both dictionaries then. 

How can one enable multiple dictionaries? I can switch between them with `jinx-languages`.

**Comment by minad** [comment]
@doolio `jinx-languages` uses `completing-read-multiple`.

**Comment by gusbrs** [comment]
> We can revisit this in a few months or a year. It may happen that I feel the need for this functionality earlier, but it is not likely.

I see you've tagged 1.0. I was really hopping you'd revisit this issue before doing so. But, well... a respectful bump then. ;-)

**Comment by minad** [comment]
At some point there will be a 2.0 ;)
