### ISSUE TITLE
just tried it, works

### ISSUE THREAD

**Issue by sjLambda** [minad/jinx#16]
I just tried it on a 900 page manuscript. It works in this one-language setup:

Latest build from emacs trunk, M-x emacs-version:
GNU Emacs 30.0.50 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.61 Version 10.13.6 (Build 17G14042)) of 2023-03-16

port install enchant2:
enchant2 @2.3.4_0+applespell
pkgconfig @0.29.2_0 (active)

enchant-lsmod-2 : 
AppleSpell (AppleSpell Provider)

**Comment by minad** [comment]
Thanks!

**Comment by sjLambda** [comment]
You may see some more submissions from me. They have to do with the manual
for jinx. I started editing it for consistency and examples. Hope you like
the edits.

BTW, ignore the earlier edits and use the latest one. I may have
accidentally sent unfinished versions while I was testing tramp problems.
Sorry for the confusion.

--S.J.

**Comment by minad** [comment]
Sure feel free to create PRs. Note the FSF copyright assignment https://github.com/minad/jinx#contributions.

**Comment by sjLambda** [comment]
I already have an FSF copyright assignment signed for GNU/Emacs. Do I need
another one just for Jinx?

**Comment by minad** [comment]
No, you don't need that.
