### ISSUE TITLE
wrong-type-argument unicode-string-p

### ISSUE THREAD

**Issue by DamienCassou** [minad/jinx#164]
Some text files when opened with the wrong encoding make jinx throw errors such as:

```
Debugger entered--Lisp error: (wrong-type-argument unicode-string-p "d\202ploiement")
  (jinx--mod-check #<user-ptr ptr=0x53375e0 finalizer=0x7f7ef7973300> "d\202ploiement")
```
[cmdline.txt](https://github.com/minad/jinx/files/14970992/cmdline.txt)

@walseb and @daanturo reported similar issues in https://github.com/minad/jinx/issues/93.

Would it be possible for jinx to deactivate itself when it fails checking a word? Currently, jinx will throw errors after errors forever and it's not obvious how to make it stop.

I have `debug-on-error` set to `t` (which [you consider being a bad idea](https://github.com/minad/jinx/issues/93#issuecomment-1646496363)) and Emacs 29.

**Comment by minad** [comment]
Please don't reopen new issues. We can continue the discussion in #93.
