### ISSUE TITLE
Feature request: support camelCased words in programming modes

### ISSUE THREAD

**Issue by serg-kozhemyakin** [minad/jinx#17]
will be good to support camelCased (and maybe PascalCased as well) words in programming modes.

**Comment by minad** [comment]
Yes, this should be supported. The backends usually don't understand CamelCase, therefore Jinx need a configurable word tokenizer.

**Comment by minad** [comment]
@agreselin Actually not due to copyright issues since this is a GNU ELPA package.

**Comment by joostkremers** [comment]
Actually, ispell does understand CamelCase. Using `flyspell-mode`, I set ispell-extra-args` to '("--camel-case")`, which works well.

BTW, I use CamelCase a lot in TSV and CSV files, and `csv-mode` is derived from `text-mode`, so if CamelCase support is added, I hope we'll be able to configure where it's available.

**Comment by joostkremers** [comment]
> @joostkremers I doubt that camel case works with every flyspell backend. 

No, definitely not, it's aspell-specific, as far as I know. I use aspell as my flyspell/ispell backend, so it works.

> This it should be handled during tokenization, which is done by Jinx.

Makes sense.

BTW, come to think of it, that's better in any case, because it would make it possible to enable this feature in jinx only when they need it. I don't need it in normal text buffers, but I do need it in my CSV files.

Perhaps it can be made dependent on `subword-mode`?

**Comment by minad** [comment]
> BTW, come to think of it, that's better in any case, because it would
> make it possible to enable this feature in jinx only when they need it.
> I don't need it in normal text buffers, but I do need it in my CSV files.
> 
> Perhaps it can be made dependent on |subword-mode|?

See `jinx-camel-modes`.

**Comment by serg-kozhemyakin** [comment]
thx for implementing this feature. it works. custom tokenizer is probably better/more flexible idea but for simple spell checking current implementation is enough for most cases from my pov. just customized it a bit during loading:

```elisp
  (use-package jinx
    :quelpa (jinx
             :fetcher github
             :repo "minad/jinx")
    :custom
    (jinx-languages '("ru_RU" "en_US"))
    (jinx-camel-modes '(prog-mode org-mode))
    :hook (emacs-startup . global-jinx-mode)
....
```

**Comment by minad** [comment]
On 3/31/23 14:17, serg-kozhemyakin wrote:
> thx for implementing this feature. it works. custom tokenizer is
> probably better/more flexible idea but for simple spell checking current
> implementation is enough for most cases from my pov.

Yes, for now that's good enough. We can generalize if more special cases
come up. I am waiting for more feedback.
