### ISSUE TITLE
Enabling `global-jinx-mode` breaks vertico in emacs daemon.

### ISSUE THREAD

**Issue by rrudakov** [minad/jinx#18]
Steps to reproduce:
- Start emacs using `emacs -Q --daemon-fg`
- Connect to daemon using `emacsclient -n -r -u -q`
- Eval the following:
```emacs-lisp
(package-initialize)
(setopt vertico-count 25)
(vertico-mode)
(global-jinx-mode)
```
- Run any command which uses completion (`imenu`, `find-file` etc)

Expected result:
- Minibuffer height doesn't change

Actual result:
- Minibuffer is being resized when number of candidates less than `vertico-count`
- Glitches in the UI

Video with example:

https://user-images.githubusercontent.com/6093590/228472111-a177f43a-3791-4752-a0ac-5df5a8a6f7d3.mov

Emacs version: GNU Emacs 29.0.60 (build 1, aarch64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68)) of 2023-03-10

**Comment by rrudakov** [comment]
Thank you for the response @minad.

After some observation I noticed that the problem occurs when you have an opened window with a lot of spelling errors (on my video it's a big org-mode file), even if you use completion in another window.

> Did you also observe such glitches before without Jinx?
no, moreover, when I disable `global-jinx-mode` the problem goes away.

> Please check if https://github.com/minad/jinx/commit/c77ddf5c8adf3edfb141e7c853a05814ae8a45e7 fixes your issue.
I've just tried. Unfortunately it doesn't fix the issue for me.

**Comment by minad** [comment]
Okay, thanks. I think I had managed to see some odd resizing at some point but I've not seen the issue anymore since then. This sounds like an Emacs bug if it happens only with the daemon. Did you never see this without the daemon?

**Comment by minad** [comment]
I looked again at your video and the display glitch is definitely an Emacs bug. This must be fixed upstream in the NS port.

**Comment by rrudakov** [comment]
Actually I could reproduce the same behavior on my Linux machine as well. So it's not the NS port bug.

To reproduce it you can try to download [this](https://git.sr.ht/~rrudakov/dotfiles/tree/feature/dotfiles-ng/item/templates/emacs.d/emacs.org) file and call `consult-org-heading` on it.

**Comment by minad** [comment]
Can you give me a precise recipe? I have not seen any such display glitches before on my machine.

**Comment by rrudakov** [comment]
I cannot reproduce it with `emacs -Q`, I guess it's something with my configuration. If I figure it out I'll post an update here. Sorry for the disturbance.

**Comment by minad** [comment]
> I cannot reproduce it with emacs -Q, I guess it's something with my configuration.

Of course. That's Emacs. ;)

**Comment by rrudakov** [comment]
OK, I've managed to reproduce it. It looks it's happening when you use completion with consult preview functionality and you have to jump pretty far from the current point. It happens only in emacsclient. 

The steps are following:
- start emacs daemon using `emacs -Q --fg-daemon`
- connect to the daemon using `emacsclient -n -r -u -q`
- apply the following configuration (I use scratch buffer for that, also I assume that vertico, consult and jinx are installed):
```emacs-lisp
(package-initialize)
(setopt vertico-count 25
	vertico-resize nil)
(vertico-mode)
(global-jinx-mode)
```
- open org file from [this](https://git.sr.ht/~rrudakov/dotfiles/tree/feature/dotfiles-ng/item/templates/emacs.d/emacs.org) link
- execute `M-x consult-org-heading`
- type capital `C` to jump to the bottom of the file

If this doesn't reproduce the problem I'm giving up :)

**Comment by minad** [comment]
I could finally reproduce this! I pushed a fix in https://github.com/minad/jinx/commit/cd0cb2b5bf4b62a8fae6a830acd937c623edbd34. Does this also fix the issue for you? This still seems to be an Emacs bug.

**Comment by rrudakov** [comment]
> Does this also fix the issue for you?

Looks like it does! Thank you!
