### ISSUE TITLE
Checking a whole buffer

### ISSUE THREAD

**Issue by tecosaur** [minad/jinx#188]
Hi Minad,

There was a dark period when I didn't actually have any spellcheck system working in Emacs, and occasionally I'm looking at files from other people. Together, this leaves me with the periodic need to spell-check an entire buffer.

Unless I've missed something, there isn't an easy way to do this with Jinx? `jinx-correct-all` is almost this, but when there's a lot of jargon in the file I find it preferable to skip through potential misspellings with `M-n`/`M-p` and look out for legitimate misspellings.

Do you think there's room for a function like `jinx-check-all` that ensures that Jinx has checked and created overlays for the given region/buffer in its entirety?

All the best,
Timothy.

**Comment by minad** [comment]
Hi Timothy!

I don't think I want to add such a command, since it doesn't seem to offer real benefits over `jinx-correct-all` and I prefer to keep the UI small and simple. But maybe a simple keyboard macro will just do what you are asking for - first invoke `jinx-correct-all` and then directly cancel the minibuffer? Alternatively you can easily add such a command yourself based on `jinx--force-overlays` to your already enormous config. :)

**Comment by minad** [comment]
One thing I would maybe consider is adding an additional argument to `jinx-next` and `jinx-previous` which forces all the overlays. But I am not entirely sure, it seems these commands already do that? So you could simply step over all misspellings right away with `jinx-next` - exactly as you asked. Or doesn't this work?

**Comment by tecosaur** [comment]
Thanks for the quick response! (as someone who's rather poor at being responsive on my repositories, you set an awfully high bar :sweat_smile:)

Yea, it is just a minor spin on `jinx-correct-all`, so I completely get it seeming not worth it to you. I suspect I'll end up "just" implementing this in my config.

The problem I have with `jinx-next` is (last I used it in a large buffer) when in the last misspelling overlay it wraps around to the first misspelling. This occurs when there are misspellings later on, but they're not fontified yet. I think you'd need to `jinx--force-overlays` on the remainder of the buffer when `jinx-next` is called on the last known overlay, but I'm not sure if this is a change you'd want to make?

**Comment by minad** [comment]
Alright, I see. I think we could add another argument to `jinx-next` and `jinx-previous` which makes sure that `:check t` is passed to `jinx--force-overlays`. Would that do it? The question is how to trigger this argument, given that the prefix argument is already in use. One could for example distinguish `C-u` and `C-4`, but this might be too disturbing. In any case one could then use a simple wrapper like `(defun jinx-force-next () (interactive) (jinx-next 1 t))`.

**Comment by tecosaur** [comment]
Something else that makes optionally augmenting `jinx-next` a little more complicated is that you often don't _know_ you're on the last misspelling overlay until you call `jinx`next` and find yourself at the first one.

**Comment by minad** [comment]
I've added an ONLY-CHECK prefix argument to `jinx-correct-all`. See https://github.com/minad/jinx/commit/55faf4c30db54b1f67376f6824c52bcafd7a4bde.

**Comment by minad** [comment]
As a nod to the excellent malpractice used in Org I've also exposed the command via `C-u C-u C-u M-$` in https://github.com/minad/jinx/commit/f85d7e9ac8e07f2a5507b0b078dae011e7abeedd.

**Comment by tecosaur** [comment]
Thanks, I anticipate getting good use out of `C-u jinx-correct-all` :slightly_smiling_face:
