### ISSUE TITLE
wiki my/jinx-save-as-ispell-localword typo or hanging paren?

### ISSUE THREAD

**Issue by shipmints** [minad/jinx#202]
I'm tiring of ```spell-fu``` high memory footprint so now trying ```jinx``` and thank you for another good package.

This is on the wiki at https://github.com/minad/jinx/wiki

```elisp
(defun my/jinx-save-as-ispell-localword (save key word)
...
      (list key word "File"))) ; hanging paren or is this function incorrect?
```

**Comment by minad** [comment]
Could be. I've not written the code in the wiki. Feel free to apply fixes there.
