### ISSUE TITLE
Please allow per-buffer words to be saved in `LocalWords` format

### ISSUE THREAD

**Issue by rrthomas** [minad/jinx#209]
Thanks to the `my/jinx-ispell-localwords` example, jinx can read my `LocalWords` lists in existing files. But it can't write to them, meaning that I can't share my files with non-jinx users.

**Comment by minad** [comment]
See https://github.com/minad/jinx/discussions/200#discussioncomment-10324961

**Comment by rrthomas** [comment]
Thanks for the pointers; sorry, I'd forgotten we'd already discussed this!
