### ISSUE TITLE
Mouse binding for `jinx-correct` in `jinx-misspelled-map`

### ISSUE THREAD

**Issue by gusbrs** [minad/jinx#21]
This is a minor suggestion. Currently, the mouse binding for `jinx-correct` in `jinx-misspelled-map` is set to `<mouse-1>`. However, this is arguably a somewhat intrusive default. Anyone who expects to just move point will do so with `<mouse-1>`, which already triggers `jinx-correct`. How about `<mouse-2>` for that?

**Comment by minad** [comment]
For now I am happy with mouse-1, like a link or button, e.g., in Org. But you can easily change this in your config. The question is rather if want a real mouse menu which lets you select directly from a list suggestions. Then we could use mouse-2 for that menu. But this feature is also on the future wish list. Maybe someone will also contribute that.

**Comment by gusbrs** [comment]
> For now I am happy with mouse-1, like a link or button, e.g., in Org. 

Ok, thanks for considering.

> But you can easily change this in your config.

I know, I already did. ;-)

**Comment by minad** [comment]
Mouse menu added in https://github.com/minad/jinx/commit/71706642cdc0031daef2c9df63cf73be8134d691.

**Comment by gusbrs** [comment]
> Mouse menu added in [7170664](https://github.com/minad/jinx/commit/71706642cdc0031daef2c9df63cf73be8134d691).

Looks good. Thank you!
