### ISSUE TITLE
Define a `jinx-mode-map`

### ISSUE THREAD

**Issue by Stebalien** [minad/jinx#22]
Please consider defining a `:keymap` for `jinx-mode`. I'd like to be able to bind a key for spell-checking but only when `jinx-mode` is enabled.

**Comment by minad** [comment]
Okay, I took look at some Emacs source. It seems not uncommon to provide empty maps, e.g., `flymake-mode-map`, `subword-mode-map` (but this one seems legacy), `hl-todo-mode-map`. Let's just do this then.

**Comment by Stebalien** [comment]
For some context, I am an evil user so I wanted to bind this to `s` but only in modes where spell-checking is enabled.

Thanks!

**Comment by gusbrs** [comment]
@minad Adding a suggestion in this regard. What do you think of also providing a keymap for `jinx-correct'? That could ease bindings for "actions" (save, skip, etc.)

**Comment by minad** [comment]
@gusbrs Let's not do this for now since the UI is not yet fixed. In the future, we could a map to move backward and forward over errors. I already overhauled the overlay infrastructure slightly in that regard, see https://github.com/minad/jinx/commit/983ffa2862209800444810916796ce8f0719bb60.
