### ISSUE TITLE
how is jinx different wo wcheck-mode?

### ISSUE THREAD

**Issue by GregorZattler** [minad/jinx#23]
Hello, could you please explain (in "Alternatives") the difference to https://github.com/tlikonen/wcheck-mode/ ?

**Comment by minad** [comment]
Wow, I totally wasn't aware of Wcheck. Therefore I cannot competently compare it to Jinx. Did you use Wcheck before? If yes, feel free to contribute a paragraph!

At first sight one big difference is that Wcheck doesn't directly bind to libenchant, but uses a separate process for the checker. Jinx uses libenchant directly to reduce the spell-checker overhead as much as possible. Besides that Wcheck seems to have different goals by allowing different kinds of checkers. Jinx on the other hand just aims to be a spell-checker, nothing else, but with performance in mind and which works out of the box. Does this help?
