### ISSUE TITLE
Allow disabling highlighting on mouseover

### ISSUE THREAD

**Issue by agreselin** [minad/jinx#24]
Hi Daniel :-) Can you make an option not to highlight misspelled words under the mouse pointer? It's a bit intrusive but I don't want to change the `jinx-highlight` face as that is good to have when I use `jinx-correct`.

**Comment by minad** [comment]
You can unset the `mouse-face` property. The same applies to all the other overlay properties. See https://github.com/minad/jinx/blob/5a858f240405032061af9ea3f0f453ef95e0c57a/jinx.el#L266.

**Comment by agreselin** [comment]
Wait, please, how do I do that?
