### ISSUE TITLE
attempting to enable jinx-mode on macos hangs

### ISSUE THREAD

**Issue by solodov** [minad/jinx#29]
On first load jinx reports that module has been successfully compiled and then beach ball of death.

This is with https://github.com/railwaycat/homebrew-emacsmacport and homebrew installed libenchant.

**Comment by minad** [comment]
I've gotten a positive report that it works on Mac, see https://github.com/minad/jinx/issues/16. Did you try emacs -Q? What is beach ball of death? Did Emacs crash?

**Comment by solodov** [comment]
Emacs just hangs, doesn't crash, macos equivalent of kill -9 is required. I experimented a bit, looks like it hangs on trying to use any of the functions in the dynamic module. Module can be loaded without any issues though.

**Comment by minad** [comment]
Do you use other dynamic modules successfully?

**Comment by minad** [comment]
Okay, I close this one, since it is probably not a Jinx issue. If more Mac-related issues come up we can investigate.
