### ISSUE TITLE
compile of module `jinx-mod.so` failed due to missing `jinx-mod.c` in MELPA package

### ISSUE THREAD

**Issue by bymoz089** [minad/jinx#3]
Fetched MELPA package jinx-20230327.48 (27.mar.2023 9:45 CET). The package was missing file  `jinx-mod.c` so compiling of `jinx-mod.so` failed.

**Comment by minad** [comment]
See https://github.com/melpa/melpa/pull/8463. In the meantime you can use the ELPA package. I recommend to prioritize packages from ELPA, see `package-archive-priorities`.

**Comment by d1egoaz** [comment]
For people like me who are using a straight and pointing directly to the repo, this is how I make it work:

```elisp
(use-package jinx
  :straight (:host github :repo "minad/jinx" :files (:defaults "jinx-mod.c" "emacs-module.h"))
  :bind (([remap ispell-word] . #'jinx-correct))
  :hook ((emacs-startup-hook . global-jinx-mode)))
```
