### ISSUE TITLE
Dictionary file names for non-standard language codes

### ISSUE THREAD

**Issue by gusbrs** [minad/jinx#31]
I'm not sure this is on `jinx`'s or `enchant`'s side. But when I choose a language which does not conform to the standard "two digit language underscore two digit cap variant", the name of the dictionary files created use just the "two digit language".

For example, in my system I have a German variant named `de_DE_frami`. If I choose this dictionary with `jinx-languages` it creates the files `de.dic` and `de.exc` in `~/.config/enchant`, instead of `de_DE_frami.dic` and `de_DE_frami.exc`.

**Comment by minad** [comment]
That's an issue of Enchant, or I wouldn't even call it an issue, since why would you want to maintain different personal dictionaries for the same language. Note that the frami dictionary has some issues on old Enchant versions, see https://github.com/minad/jinx/issues/5.

**Comment by gusbrs** [comment]
I was afraid so. And I just used `de_DE_frami` as an example. My actual use case is that I'm trying to keep two versions of `pt_BR`, one for regular documents, and one for documents where I have a mixture of current and old spelling of Portuguese. So precisely what I want to do is to keep them separate, and use both dictionaries just for documents where that is meaningful. I can create a "dummy" (empty) dictionary named `pt_BR_old` (there is no such dictionary available, as far as I know), so that I can use both `pt_BR` and `pt_BR_old` which boils down to the standard `pt_BR` dictionary, plus some saved words for old spelling. But, admittedly, this is an atypical use case. I guess I'll have to live with `pt.dic` and `pt.exc`. Thanks!

**Comment by minad** [comment]
As far as I understand Enchant can also support additional personal dictionaries, separate from the ones associated with languages. But it is not entirely clear if this functionality is to be preferred over the other personal dictionaries. This functionality is not exposed by Jinx and for now I also don't plan to do this soon, because as you said, it is a special use case.

**Comment by gusbrs** [comment]
I got slightly better results with `ptold_BR`, probably by luck though. Thanks again!
