### ISSUE TITLE
Separate languages in the mode lighter using a non-whitespace character

### ISSUE THREAD

**Issue by agreselin** [minad/jinx#39]
As the lighter is taken straight from `jinx-languages`, when multiple languages are in use they are separated by a space, just like modes are separated from one another:

![Screenshot from 2023-04-13 13-23-23](https://user-images.githubusercontent.com/22297948/231744249-87b5af96-cd59-42fd-88d8-823e341f9a8a.png)

Imo it would be better to separate the languages using another character, e.g. a comma.

**Comment by minad** [comment]
I introduced a more verbose lighter. You can also customize the lighter in the `minor-mode-alist` if you want to change the formatting, e.g., displaying `jinx-languages` only separated by comma.
