### ISSUE TITLE
How to disable check Chinese character

### ISSUE THREAD

**Issue by Jousimies** [minad/jinx#4]
After I enable jinx-mode in org-mode, all Chinese chars were displayed error as below pic show.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/72933939/227892795-fdaf5605-eb3f-42e7-b19e-f256328cf5ed.png">

Any help ?

**Comment by minad** [comment]
Multi language support is a notable feature of Jinx. You can set this via `(setq jinx-languages '("en" "cn"))`. Please let me know if this works!

**Comment by Jousimies** [comment]
Add "cn" to `jinx-languages` not work as expect.

But I add `\cc` regexp to `jinx-exclude-regexps`, it worked.

Thank you.

**Comment by minad** [comment]
I see. Could you please enlighten me about spell checkers in Chinese? Do you also have a Chinese dictionary installed which is picked up by Aspell/Hunspell etc? Chinese words are usually short and it seems logographic writing systems are not supported by these packages (http://aspell.net/0.61/man-html/Languages-Which-Aspell-can-Support.html).

**Comment by minad** [comment]
@Jousimies Thanks, so for Chinese it boils down to some complex checking like checking the grammar.

**Comment by minad** [comment]
Instead of adding a regexp to `jinx-exclude-regexps` one can also configure word characters in `jinx--base-syntax-table` via `modify-syntax-entry`.

**Comment by dwla** [comment]
> Add "cn" to `jinx-languages` not work as expect.
> 
> But I add `\cc` regexp to `jinx-exclude-regexps`, it worked.
> 
> Thank you.

Could you do me a favor to show me the code of "add '\cc' regexp t 'jinx-exlucde-regexps'"?
