### ISSUE TITLE
jinx doesn't show suggestions from dictionary

### ISSUE THREAD

**Issue by zhenwu0728** [minad/jinx#41]
I started to try jinx today but found that when I run `jinx-correct` there's no `suggestions from dictionary` and `accept and save word` as showed in README (see screenshot below).

<img width="898" alt="Screenshot 2023-04-17 at 3 58 19 PM" src="https://user-images.githubusercontent.com/46291075/232596807-bfb77a4e-31e5-45a7-a04d-b6dd120eb262.png">

I use `straight.el` for pkg management, below is what I use to install jinx
```
(use-package jinx
  :straight t
  :hook (emacs-startup . global-jinx-mode)
  :bind ([remap ispell-word] . jinx-correct))
```

I also have `enchant` and `pkgconfig` installed.

I'm new to emacs, would be grateful is someone can help me out.

**Comment by minad** [comment]
You should also install either Hunspell, Aspell and the relevant dictionaries. Enchant uses one either Hunspell or Aspell as backend for English. For example on my system I have libhunspell, hunspell and hunspell-en-us installed. I hope this helps.

**Comment by zhenwu0728** [comment]
Thanks for your quick reply! @minad 
I have both aspell and hunspell installed via `homebrew`.

**Comment by minad** [comment]
Okay, so it seems checking works properly? Only the suggestions are missing?

**Comment by zhenwu0728** [comment]
Yes, you can see the red underlines in the screenshot.

**Comment by zhenwu0728** [comment]
Ah, yes! I just started a vanilla-emacs configuration and haven't got to the completion part. I'll try if that's the problem. Thanks!

**Comment by minad** [comment]
Okay, let me know how it goes. The Jinx UI is currently non-ideal if you don't use Vertico or a similar UI. Maybe a Transient would be a better fit for Jinx. There are long UI discussions in #9 and #30.
