### ISSUE TITLE
Guidance for integration with context-menu-mode?

### ISSUE THREAD

**Issue by david-christiansen** [minad/jinx#45]
This is a great package, thanks!

I tend to use the mouse regularly to move the cursor around, and having `<mouse-1>` activate spelling correction gets in the way of that muscle memory. I've tried to have `jinx` instead integrate with Emacs' built-in context menu by doing the following:
 * Adding `(define-key jinx-misspelled-map (kbd "<mouse-1>") nil)` to the package configuration (this doesn't turn off the button cursor, but it at least lets me move the cursor onto a misspelling with the mouse)
 * Define `jinx-context-menu` as below, and add it to `context-menu-functions`

```
  (defun jinx-context-menu (menu click)
    (save-excursion
      (mouse-set-point click)
      (let* ((clicked-point (point))
             (jinx-overlays (cl-remove-if-not (lambda (o) (eq (overlay-get o 'category) 'jinx)) (overlays-at clicked-point)))
             (command
              (lambda ()
                (interactive)
                (goto-char clicked-point) (jinx-correct))))
        (when jinx-overlays
          (define-key menu [jinx-correct-mouse] `(menu-item "Correct Spelling" ,command)))))
    menu)
```

This is almost what I'd like. The downside is that the completion interface in Emacs ends up being tiny until I type something, whereas `M-$` on the same point in the buffer brings up a completion interface.

This is using Vertico and Marginalia.

Is there a better way to add this package to the Emacs context menu?

**Comment by minad** [comment]
Thanks! Ideally the context menu could directly offer the correction candidates such that one could just use an entirely mouse-driven workflow if that is desired. I believe Flyspell itself comes with such code. 

Personally I am not using the context menu since I find it a bit overloaded (I guess I have to dig into it at some point to see if I could customize it to my liking). Then I also rely very much on Embark which is like a keyboard-driven context menu at point. That's the reason why Jinx currently lacks proper mouse support.

**Comment by david-christiansen** [comment]
Flyspell does indeed to that - I unfortunately ran out of time after getting this far and likely can't tweak it anymore until May.

I wonder - do you think that many regular mouse users want `<mouse-1>` to do the correction action rather than moving point? Perhaps the configuration should be a bit more transparent/documented?

**Comment by minad** [comment]
> I wonder - do you think that many regular mouse users want <mouse-1> to do the correction action rather than moving point? Perhaps the configuration should be a bit more transparent/documented?

Yes, probably. I may add a context menu at some point to Jinx. But for me personally the feature doesn't have high priority.

**Comment by david-christiansen** [comment]
All right - I'll see if I can figure out a proper mouse-driven interface. Won't be until May, as I've got a big deadline approaching :-) Thanks!

**Comment by minad** [comment]
I close this, since this feature is not planned right now. If you or someone else is interested in implementing this, I welcome a PR. Flyspell can be used as reference implementation.

**Comment by minad** [comment]
I added a mouse menu in https://github.com/minad/jinx/commit/71706642cdc0031daef2c9df63cf73be8134d691.

**Comment by david-christiansen** [comment]
Wow! Thanks! As you can see, I didn't get to it in May :-)
