### ISSUE TITLE
Undo issues with `C-u  M-x jinx-correct`

### ISSUE THREAD

**Issue by gusbrs** [minad/jinx#46]
Hi @minad , following discussion at https://github.com/minad/jinx/issues/43#issuecomment-1514782494, I open a separate issue with a recipe for the `undo` problems with `C-u M-x jinx-correct` described there.

Starting with `emacs -Q`, paste the following in the scratch buffer and `eval-buffer`.

```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/compat-29.1.4.1")
(add-to-list 'load-path "~/.emacs.d/elpa/jinx-0.6.0.20230418.182018")
(require 'jinx)
(global-jinx-mode)
```
Now `M-<`, `C-u M-x jinx-correct RET`, `1` to correct "emacs" into "Emacs", `1` again to correct "elpa" into "EPA". Now `C-/`: get message "No further undo information", the undo is not carried out. Switch windows with `C-x o` and `C-/` again, and both "elpa" and "emacs" are undone in one undo step.

Emacs version is "GNU Emacs 29.0.90 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-04-10"

**Comment by minad** [comment]
Okay, I see. I fixed the issue, such that corrections are not undone at once. However I wonder about your "No further undo information" message. Do you call undo while the minibuffer is still open? Undo must always be called within the original buffer.

**Comment by gusbrs** [comment]
> Okay, I see. I fixed the issue, such that corrections are not undone at once.

Thank you.

> However I wonder about your "No further undo information" message. Do you call undo while the minibuffer is still open? Undo must always be called within the original buffer.

Yes I did, as described in the recipe. Perhaps I'm spoiled by somewhere which took care of that for me, I'm not sure. But, it makes sense that `undo` there would refer to what I had typed in the minibuffer, not the correction. In which case, there is really no undo information.
