### ISSUE TITLE
Jinx interprets italised /Word/ as a mispelling.

### ISSUE THREAD

**Issue by artelse** [minad/jinx#56]
Topic should be self-explanatory.

**Comment by minad** [comment]
I cannot observe this. I'd need a minimal recipe to reproduce the issue.

**Comment by artelse** [comment]
Have been trying to debug this problem because I assume it to be in my config, but haven't found why this is happening. Any problem solving hints? Thanks!

**Comment by minad** [comment]
You can check if slash is treated as word character for some reason. Check `(char-syntax ?/)` and `(syntax-class-to-char (car (aref jinx--syntax-table ?/)))` in the buffer where you use `jinx-mode`. In my setup the return value is `?_` which denotes a symbol character, but not `?w` which would denote a word character.

**Comment by artelse** [comment]
The first check yields `?_`, but the second test `?w`. So something not correct with jinx--syntax-table?

**Comment by minad** [comment]
This means that your dictionary incorrectly reports slashes as word constituents. Either your libenchant version has some issue or the spell checking backend (Aspell, Hunspell, ...) reports this incorrectly. You can modify the syntax table like this:

~~~ elisp
(advice-add #'jinx--load-dicts :after
            (lambda () (modify-syntax-entry ?/ "_" jinx--syntax-table)))
~~~

**Comment by artelse** [comment]
Have been testing enchant, hunspell and aspell setup. When I test those on the terminal with a test file containing words with spelling mistakes and words with the dreaded `/` prefix, all of these tests run as they should. So I think we can rule out a problem with my spelling setup. Manually adding the problem chars as suggested seems no more than a workaround, not solving the issue. Might there be something fishy going on with the `jinx--syntax-table` gen perhaps?

**Comment by minad** [comment]
No, something is broken in your spelling setup. Jinx asks Enchant for additional word characters. If Enchant incorrectly reports `/` as a word constituent, that's a problem on a lower level and not a problem of Jinx. It depends on your dictionary etc. There could also be something wrong with the retrieval of the wordchars, but in my setup this works as expected. You can try to debug there.

https://github.com/minad/jinx/blob/fd0ec59222c6e26234c5f347477bef69e563e46d/jinx-mod.c#L143-L155

**Comment by minad** [comment]
Please also check: `(syntax-class-to-char (car (aref (standard-syntax-table) ?/))) -> ?_`.

**Comment by artelse** [comment]
Looks like it is indeed something on my end. When I do the second test, it reports: `Lisp error: (void-variable jinx--base-syntax-table)`. So jinx got not initialized properly? Also on my `config.org` file the error doesn't occur while on a regular org file it does have the `/` problem. This needs a thorough dig through my setup/ emacs config; I've already looked for a paren mismatch, but nothing found yet. Will create a minimal emacs config and work up from there. Thanks so far, will report back when I've found the problem.

**Comment by artelse** [comment]
Some more testing, I set multiple languages like so: `(setq jinx-languages '("en_US" "nl_NL"))` When I enable `jinx-mode`, I get this error: `Wrong type argument: stringp, ("en_US" "nl_NL")`.
Now when I set `"en_US nl_NL"` in `customize-group`, jinx checks both languages correct except when surrounded with the dreaded `/`. 
This is in a new minimal setup.

**Comment by minad** [comment]
Okay, I installed `hunspell-nl` and tested this. I set `jinx-languages` to `nl_NL` (the variable must be a string, see the docstring). Then I evaluate:

~~~ elisp
(jinx--mod-wordchars (car jinx--dicts)) => "'’0123456789ĳ.-\\/+"
~~~

This means the dictionary (incorrectly?) reports slash as a word character. When I try `enchant-2` and `hunspell` on the command line I also get incorrect results:

~~~ shell
# Good
echo 'Rinus Dijkstra, beter bekend onder zijn artiestennaam Zanger Rinus, is een Nederlandse zanger.' | enchant-2 -a -d nl /dev/stdin

# Good
echo 'Rinus Dijkstra, beter bekend onder zijn artiestennaam Zanger Rinus, is een Nederlandse zanger.' | hunspell -a -d nl /dev/stdin

# /Zanger and /Rinus are displayed as misspelled
echo 'Rinus Dijkstra, beter bekend onder zijn artiestennaam /Zanger Rinus/, is een Nederlandse zanger.' | enchant-2 -a -d nl /dev/stdin

# /Zanger and /Rinus are displayed as misspelled
echo 'Rinus Dijkstra, beter bekend onder zijn artiestennaam /Zanger Rinus/, is een Nederlandse zanger.' | hunspell -a -d nl /dev/stdin
~~~

I recommend to adjust the syntax table manually to fix the issue as I already mentioned in https://github.com/minad/jinx/issues/56#issuecomment-1527929071.

~~~ elisp
(advice-add #'jinx--load-dicts :after
            (lambda () (modify-syntax-entry ?/ "_" jinx--syntax-table)))
~~~

**Comment by artelse** [comment]
Thanks for finding this out, hunspell-nl is indeed wrongly reporting this as an error. I've asked on the hunspell-nl repo what is going on. For now I'll resort to the work around. Thanks again!
