### ISSUE TITLE
Add word to multiple language personal dictionaries

### ISSUE THREAD

**Issue by meliache** [minad/jinx#63]
Asking for advice:

My `jinx-languages` contain English and German and currently I maintain separate personal dictionaries for both, but some new words like names are shared between both. Is there an easy way to add a word to two dictionaries or maybe have one shared dictionary in addition to the separate language dictionaries?

In the README you write 

>  It is possible to symlink different personal dictionaries such that they are shared by different spell checkers. See the Enchant manual for details.

I could link my English and German personal dictionaries together, but then I would loose the ability to add language-specific words to only one or the other, so I want to maintain separate personal dictionaries. Though having one shared dictionary in addition to the separate ones would also work, just don't know how to implement that either.

An easy approach is just to add new words to both personal dictionaries. Just using `jinx-correct` twice doesn't work, because after I add the word to the personal dictionary in one language, it's not marked as a mistake anymore, so I would have to change the language before using `jinx-correct` again or manually edit the dictionary files.

One thing that I tried naively is to narrow the selection to the word-adding actions and then run `embark-act-all` with `jinx-correct`, but of course this doesn't work as jinx-correct doesn't know what to do with each candidate. `completing-read-multiple` might be a nice interface to add a word to multiple dictionaries, but I would not use that for `jinx-correct` as it doesn't make sense for corrections, this would only make sense if we had an interactive command specifically for adding a word to personal dictionaries.

I think the underlying issue is clear but I'm not sure how to best approach it.

**Comment by minad** [comment]
Hi! You can write your own variant of jinx--save-personal which saves in all the dictionaries instead of only a single dictionary. Then register this function in jinx--save-keys. If you figure this out and if you like feel free to add your solution to the wiki.

**Comment by minad** [comment]
Another maybe better solution would be to add an additional fake language "names" to jinx-languages and add names there. However I am not sure which tweaks are needed for libenchant to make this work.

Yet another solution would be to add words to another separate dictionary file and then load that file into jinx--local-words. 

There are multiple possibilities but to me none really stands out as the best solution.
