### ISSUE TITLE
Disable spell check for other languages

### ISSUE THREAD

**Issue by psionic-k** [minad/jinx#65]
Couldn't find an option to skip checking on words not in the configured langauge.  I have to turn off spell check if there's a lot of CJK characters etc.

**Comment by minad** [comment]
See #4 regarding disabling CJK characters. You can also define the characters as non-word characters in `jinx--base-syntax-table`.

**Comment by minad** [comment]
@psionic-k @Jousimies Would it make sense to exclude such character ranges by default?

**Comment by psionic-k** [comment]
If the languages are not supported or active, the misspelling indication can't mean anything, so it should be excluded.

If a character doesn't occur in my dictionaries, I don't think the word is from a language I have support for.

The lack of a dictionary should be apparent to users when they knowingly misspell a word.  If they don't edit in a language and will never see the false positive, there was also no use for checking the spelling of text they won't / can't edit.

**Comment by minad** [comment]
I think it only makes sense to exclude character ranges by default in Jinx which are not used to create "checkable" words. As @Jousimies told me, spell checking Chinese text is like grammar checking, such such that it cannot be handled by simple word-based spell-checkers like Enchant and Jinx. We could therefore decide to exclude these character ranges. Currently Jinx only excludes character ranges for Emojis and other symbols.

**Comment by psionic-k** [comment]
Quick trivia, Korean has somewhat variable spacing in practice.  Japanese has mostly none.  I don't think traditional spell-checkers are good at these languages.  We probably will be waiting on tiny transformers (GPT-like) to have good practical benefits.
