### ISSUE TITLE
spelling errors are shown for yaml identifiers 

### ISSUE THREAD

**Issue by ParetoOptimalDev** [minad/jinx#69]
I think these should be ignored. Emacs 30. I tried both `yaml-mode` and `yaml-ts-mode` and still see the issue.

I believe that only comments should be spell-checked?

**Comment by minad** [comment]
Fixed. yaml-mode is wrongly classified as a text-mode. Maybe I should rather treat such mistakes as wontfix. Let's see if there are many modes which are wrong like this.
