### ISSUE TITLE
macos jinx installs but jinx-mode.c is not found

### ISSUE THREAD

**Issue by ChauhanT** [minad/jinx#70]
Hi, 
I have been able to install jinx on emacs 28.2 on macos 13.2. After installation, when I try to run `jinx-languages`, I get the following error:

```
jinx--load-module: Jinx: jinx-mod.c not found
```

Not sure what's going on, and any help would be awesome. Thank you!

**Comment by minad** [comment]
It seems that you didn't install Jinx correctly. jinx-mod.c should be located next to jinx.el in the ELPA installation directory. I recommend that you install Jinx via `package-install` from ELPA.

**Comment by ChauhanT** [comment]
Ah right. So I should not use straight.el for it ? My current config is 

```
(use-package jinx
  :straight (:type git :host github :repo "minad/jinx")
  :hook (emacs-startup . global-jinx-mode))
```

I also installed enchant-2 with homebrew like so: 

```
brew install enchant
```

This installs enchant at `/opt/homebrew/bin/enchant-2`. 

Does this seem about right ?

**Comment by ChauhanT** [comment]
To straight.el users who might end up here with a config similar to mine. The solution is: 

'jinx-mod.c' and 'emacs-module.h' need to be copied into 'straight/build/jinx' from 'straight/repos/jinx'.

Hope this helps!

**Comment by minad** [comment]
Any insight on why Straight doesn't install jinx-mod.c by default? Jinx isn't the only package with c files, there is for example also the highly popular vterm package. Does this also need special treatment?

**Comment by ChauhanT** [comment]
No idea. I was just glad to get it working. The flyspell-correct hell was driving me mad. Thank you for jinx, it's a fabulous addition to modern packages. Hopefully you will maintain it for a while. 

I'm the developer of emacs-groundup. jinx is definitely making it to v2.0. It's a godsend!
