### ISSUE TITLE
Better annotation for `jinx--save-personal`

### ISSUE THREAD

**Issue by gusbrs** [minad/jinx#73]
This is a small suggestion, but I think of interest.

Since you added support for annotations in `vertico-grid` and suggested its use in the Readme, I've been enjoying it, and it really fits in with the speed keys.

However, bumping `vertico-grid-annotate` to a high value may not produce ideal results, and leaving it at a smaller number (20 currently suggested in the docs) results in the name of the dictionary being frequently truncated, which may particularly complicate things with multiple dictionaries.

How about using `"‘%s’ personal"` instead of the current `"Personal ‘%s’"` for the annotation? This wouldn't eliminate the issue, of course, but would mitigate it, in that if truncation occurs, it will affect first a less valuable piece of information.

**Comment by minad** [comment]
Hmm, I see your point but to my eyes "‘en_US’ personal" just looks wrong :shrug:

**Comment by gusbrs** [comment]
Fair enough. :-) Thanks for considering.

**Comment by gusbrs** [comment]
I see you did shorten it a little, thanks!

Another idea, how about "Save" instead of "Personal", half the length, quite traditional...

**Comment by minad** [comment]
Save is too generic. The dictionaries are called "personal" that's the Enchant/Ispell jargon.
