### ISSUE TITLE
Setting dictionaries with variants 

### ISSUE THREAD

**Issue by haji-ali** [minad/jinx#74]
Is it possible to use jinx and enchant with dictionary variants? I tried
`(setq jinx-languages "en_GB-ize")`

but `factorize` is still being marked as wrong and `factorise` is suggested. I am using `aspell` as a provider and I am sure that `en_GB-ize` is available as (it is listed when I call `aspell --help`).

**Comment by minad** [comment]
Jinx asks Enchant for dictionaries and lists them in the `jinx-languages` command. You probably have to configure Enchant differently such that it also lists these variants. See the file enchant.ordering and https://github.com/minad/jinx#enchant-backends-and-personal-dictionaries.

**Comment by haji-ali** [comment]
A note to future wanderers: This was not possible before but the new Enchant version 2.6.1 supports language variants (at least when using aspell as backend).
