### ISSUE TITLE
jinx-correct search direction

### ISSUE THREAD

**Issue by walseb** [minad/jinx#75]
Hello! Thank you so much for this package!

Currently, `jinx-correct` starts by searching for spelling mistakes behind the cursor, unless there are none in view, then it searches forward.

While this behavior is useful right as you are typing, when editing it can be annoying. For example, if your cursor is one character behind a word, and you try to correct it, it may instead correct a word far away.

It would be useful to have the option to set it to search forward instead, or even an option to have it search for the word in closest proximity, whether behind or ahead of the cursor.

**Comment by minad** [comment]
Thanks for the proposal. 

I prefer to keep things simple and not offer a configuration option for the direction. The UI may not yet be in its final form and I want to gather more experience first. There have already been a few long UI design discussions. Initially the command moved to the misspelling in closest proximity but I changed this to consistently move backward.

You should be able to use `jinx-next` and `jinx-correct` to write a custom command or a keyboard macro which first moves to the next misspelling in case you generally prefer that.

**Comment by walseb** [comment]
I see, thanks for the reply!
