### ISSUE TITLE
Usage together with Vertico, vertico-multiform-mode is not defined.

### ISSUE THREAD

**Issue by Sinthoras7** [minad/jinx#76]
For using it together with Vertico you suggest configuring 
```
(add-to-list 'vertico-multiform-categories
             '(jinx grid (vertico-grid-annotate . 20)))
(vertico-multiform-mode 1)
```
I tried to mimic this and got a void-function-error, because vertico-multiform mode is not defined. Then I also looked at vertico.el from the vertico package and a quick search showed, that this makes sense, as the phrase "vertico-multiform" is not in vertico.el.

Could it be that this multiform-mode existed in a past version of vertico, but not anymore?

**Comment by minad** [comment]
vertico-multiform exists in the Vertico package from GNU ELPA if you install it via package-install.

**Comment by Sinthoras7** [comment]
Ah, it is an extension of Vertico. I am sorry, I thought it was deprecated, and thus opened this issue. 
Now I just get the error `Symbol’s function definition is void: grid`, but I am sure it is my fault and not the packages, so you don't have to think about it.
