### ISSUE TITLE
Excessive fontification

### ISSUE THREAD

**Issue by walseb** [minad/jinx#79]
Hello!

Currently, this package fontifies the entire buffer at times when enabled.

However, functions like `jit-lock-fontify-now` takes a buffer range as an argument. Could the calls to it be modified to only fontify the visible area without issue? 

When viewing large buffers, this package freezes my Emacs instance during fontification. 

I'm not familiar with the inner workings of this package, so I don't know if doing so could cause issue.

Thoughts?

Thanks!

**Comment by minad** [comment]
Jinx only fontifies the whole buffer when explicitly asked to do so via `C-u M-x jinx-correct`. In which other scenario do you observe issues?

**Comment by walseb** [comment]
Yes, that's right, it only occurs when I call `jinx-correct`. I thought it might be a bug in my config, causing it to only happen when called. The file I'm visiting is a 150 000 line org file with org-modern enabled, and my computer is rather slow.

**Comment by minad** [comment]
Okay. 150k lines is excessively large. It is true that jinx-correct with prefix argument fontifies the whole buffer for whole buffer check. Without prefix argument it only fontifies the visible portion of the buffer. We could improve the whole buffer check to fontify the buffer in chunks and perform the spell check in chunks. I am happy to accept a patch which implants chunking for large buffers, but I don't need this right now myself.

**Comment by minad** [comment]
I just saw that `jinx--force-overlays` did not take the boundaries into account for fontification, which it should do of course. I am pretty sure it did that in the past before I made the changes for indirect buffers.

**Comment by walseb** [comment]
Excellent, I saw that there is still a fontification call that fontifies the entire buffer needlessly. I have addressed it in #84.

**Comment by minad** [comment]
> Excellent, I saw that there is still a fontification call that fontifies the entire buffer needlessly. I have addressed it in https://github.com/minad/jinx/pull/84.

Makes sense. However I wonder if this refontify call leads to observable performance problems, since `jit-lock-refontify` should be a very cheap function. It just sets the `fontified` property to nil inside the buffer.

**Comment by walseb** [comment]
Good point, I'm not sure. It might cause slowness if the org cache relies on that property. I haven't tried it without that patch.
