### ISSUE TITLE
feat request: move cursor to next error

### ISSUE THREAD

**Issue by Jousimies** [minad/jinx#8]
As title.

After correct one mis spelled word, continue to correct next one.

**Comment by minad** [comment]
You can use `C-u M-x jinx-correct`. The command will start at the beginning of the buffer, but I could also change it to start at the next error and continue from there.

**Comment by Jousimies** [comment]
Ok， thank you for you great work.

It will be better to move to next error.

By the way, can use number to choose the correct one?

**Comment by minad** [comment]
> It will be better to move to next error.

Okay, I will try this.

> By the way, can use number to choose the correct one?

See `vertico-indexed-mode` and `vertico-multiform-mode`.

**Comment by minad** [comment]
> It will be better to move to next error.

Okay, I will try this.

> By the way, can use number to choose the correct one?

See `vertico-indexed-mode` and `vertico-multiform-mode`.
