### ISSUE TITLE
Save to abbrev

### ISSUE THREAD

**Issue by shouya** [minad/jinx#81]
I switched to Jinx few weeks ago and was extremely satisfied. However, a small flyspell feature I miss a lot is `flyspell-abbrev-p`. In short, the flag will enable saving any corrections made into the abbrev table, so next time the misspelled word will be automatically substituted by abbrev-mode, without the need to correct it. What's the best way to implement this with jinx?

I am expecting something like a `jinx-correct-hook` where I can easily get the word and user's choice. I also looked into advicing `jinx--correct` but it was a little too complex to patch.

**Comment by shouya** [comment]
It works. Thank you!

Just pasting my patch here in hope of it can someone save a few minutes.

```emacs-lisp
(defun shou/jinx--add-to-abbrev (overlay choice)
    "Add word -> CHOICE to global abbrev table. (word is under OVERLAY.)"
    (let ((word (buffer-substring-no-properties
                 (overlay-start overlay)
                 (overlay-end overlay))))
      (message "%s -> %s" word choice)
      (define-abbrev global-abbrev-table word choice)))

  (advice-add 'jinx--correct-replace :before #'shou/jinx--add-to-abbrev)
```

**Comment by minad** [comment]
Thanks, I added your snippet to the wiki: https://github.com/minad/jinx/wiki#save-misspelling-and-correction-as-abbreviation
