### ISSUE TITLE
Jinx compatibility with Apple Silicon M1?

### ISSUE THREAD

**Issue by jaydixit** [minad/jinx#82]
I'm on a newer MacBook Pro. When I install Jinx, I get an error (pasted below).

I did successfully install enchant via `brew install enchant`:
```
==> enchant: stable 2.5.0 (bottled)
Spellchecker wrapping library
https://abiword.github.io/enchant/
/opt/homebrew/Cellar/enchant/2.5.0 (29 files, 406.2KB) *
  Built from source on 2023-05-26 at 01:17:48
==> Dependencies
Build: pkg-config ✔, groff ✔
Required: aspell ✔, glib ✔
```

...but maybe it's the wrong version. 

Trying to solve this myself, I found this: https://github.com/pyenchant/pyenchant/issues/265 ...but I'm not sure how to apply the workaround there.

I tried running PYENCHANT_LIBRARY_PATH=/opt/homebrew/lib/libenchant-2.2.dylib and DYLD_LIBRARY_PATH=/opt/homebrew/lib/ as suggested there, but it didn't work.

This is the error: 

```
gcc -I. -O2 -Wall -Wextra -fPIC -shared -o jinx-mod.dylib jinx-mod.c -I/usr/local/Cellar/enchant/2.5.0/include/enchant-2 -I/usr/local/Cellar/glib/2.76.3/include -I/usr/local/Cellar/glib/2.76.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre2/10.42/include -L/usr/local/Cellar/enchant/2.5.0/lib -lenchant-2
ld: warning: ignoring file /usr/local/Cellar/enchant/2.5.0/lib/libenchant-2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_enchant_broker_free_dict", referenced from:
      _jinx_free_dict in jinx-mod-8d2637.o
  "_enchant_broker_init", referenced from:
      _jinx_dict in jinx-mod-8d2637.o
      _jinx_langs in jinx-mod-8d2637.o
  "_enchant_broker_list_dicts", referenced from:
      _jinx_langs in jinx-mod-8d2637.o
  "_enchant_broker_request_dict", referenced from:
      _jinx_dict in jinx-mod-8d2637.o
  "_enchant_dict_add", referenced from:
      _jinx_add in jinx-mod-8d2637.o
  "_enchant_dict_check", referenced from:
      _jinx_check in jinx-mod-8d2637.o
  "_enchant_dict_describe", referenced from:
      _jinx_describe in jinx-mod-8d2637.o
  "_enchant_dict_free_string_list", referenced from:
      _jinx_suggest in jinx-mod-8d2637.o
  "_enchant_dict_get_extra_word_characters", referenced from:
      _jinx_wordchars in jinx-mod-8d2637.o
  "_enchant_dict_suggest", referenced from:
      _jinx_suggest in jinx-mod-8d2637.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Jinx: Compilation of jinx-mod.dylib failed
```

**Comment by minad** [comment]
Yes, it seems your version of libenchant is incompatible. I cannot help since I don't have a Mac around, but I've got reports that Jinx works on Macs (#16).

**Comment by incandescentman** [comment]
Sounds good. Should we leave the issue open then, so others will know there's an open issue they can potentially help with, instead of closing it as completed? (Since it isn't completed?)

**Comment by swamijee** [comment]
This has nothing to do with this package or enchant. The root of the problem is how emacs manages path.

So you have to check two things:

1. Install `pkg-config`. If you installed enchant using `brew`, you have to install `pkg-config` using brew as well. 
2. `PATH` and `zsh`: I am one of the three people probably that still uses bash :). But the default env shell in emacs for OSX is zsh. And that is where emacs gets its PATH settings from. Ensure that your `.zprofile` has appends the brew path appropriately. If you're not comfortable doing that, you can just add the brew path (`/opt/homebrew/bin`) to `/etc/paths`

Once you have done both the steps, the compilation of the dylib should work as expected, and the package should automatically load.

**Comment by jeff-phil** [comment]
@jaydixit  Based on this message from your output, I notice a few clues:

`ld: warning: ignoring file /usr/local/Cellar/enchant/2.5.0/lib/libenchant-2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64`

* `/usr/local/Cellar` indicates that you are using the `x86_64` - or _non-Apple Silicon_ - version of Homebrew, and which installed the `x86_64` `enchant` package.  The `arm64` (Apple Silicon) Homebrew now installs to `/opt/homebrew` location.
* The `ld` message also is letting you know that it is trying to link to that `x86_64` version of enchant, but targeting the `arm64` (default for Apple Silicon) as the output for the dynamic module.   If you want to stay on `x86_64` version of Homebrew (probably not what you want), then you will need to add `-arch x86_64` option.  Again, probably not what you want, but maybe you have valid reasons.
* Whatever you do, you'll want to match the CPU architecture for your Emacs install.

In you favorite search engine, look up _homebrew migrate from intel to m1_ to see how to install and migrate your `x86_64` brew packages to `arm64`.

**Comment by Singletoned** [comment]
> 1. Install `pkg-config`.

This fixed it for me.  Thanks @swamijee !
