### ISSUE TITLE
How to disable jinx in javascript imports?

### ISSUE THREAD

**Issue by danielpza** [minad/jinx#85]
Is there a way to disable spell checking on some special "strings", in this case javascript require/imports specifiers. Example:

```js
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
```

![image](https://github.com/minad/jinx/assets/17787042/298cab36-4504-4b6b-b84f-1649c66cee66)

the `dnd` and `backend` strings are being highlighted as incorrect, but they cannot be corrected by the user so there's not need to highlight them.

**Comment by minad** [comment]
No, this is not possible right now unfortunately. There are multiple possibilities to improve this:

1. Add a custom predicate, which jumps to the beginning of the line and searches for the keyword "import".
2. Add limited look behind support to the regexp exclusion mechanism to Jinx
3. Add a treesitter-based exclusion mechanism to Jinx
4. Extend font locking to distinguish user strings from other special strings via different faces (should happen in the mode or via an extension of the mode, possibly also via treesitter) 

Option 1 is the simplest approach, which you could add to your config right away. The downside is that we cannot add a large number of such predicates for all various modes to Jinx. Option 2 seems the most promising approach for Jinx. We may add this I'm the future.
