### ISSUE TITLE
Jinx in Guix

### ISSUE THREAD

**Issue by nanounanue** [minad/jinx#86]
Hi, just installed  the following packages in my computer:

```
                     "enchant"
                     "pkgconf"
```

and defined the following package:

```scheme
(define-public emacs-jinx
  (package
    (name "emacs-jinx")
    (version "0.8")
    (source (origin
              (method url-fetch)
              (uri (string-append "https://elpa.gnu.org/packages/jinx-" version
                                  ".tar"))
              (sha256 (base32
                       "19dgp312jvpy3k0xq0r033jfhnyrl8xfv3q2djwv9s7883483srn"))))
    (build-system emacs-build-system)
    (propagated-inputs (list upstream:emacs-compat))
    (home-page "https://github.com/minad/jinx")
    (synopsis "Enchanted Spell Checker")
    (description "")
    (license license:gpl3+)))
```

But when I run `jinx-mode` I am getting the following error:

```elisp
Debugger entered--Lisp error: (error "Jinx: jinx-mod.c not found")
  error("Jinx: %s not found" "jinx-mod.c")
  jinx--load-module()
  jinx-mode(toggle)
  funcall-interactively(jinx-mode toggle)
  command-execute(jinx-mode record)
  execute-extended-command(nil "jinx-mode" nil)
  funcall-interactively(execute-extended-command nil "jinx-mode" nil)
  command-execute(execute-extended-command)
```

My emacs version is `GNU Emacs 29.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)`

Any ideas?

**Comment by minad** [comment]
The file jinx-mod.c should be located next to jinx.el. Then the file will be found and automatic compilation should work. 

But for Guix or Nix you probably want to compile the module earlier during installation? I suggest you look into other Guix packages which utilize native Emacs modules. It would be great if Jinx could be packaged for Guix. Maybe the Guix Emacs maintainers could also help?

**Comment by nanounanue** [comment]
Thank you! I will check that :)

**Comment by mekeor** [comment]
I managed to successfully build Jinx using Guix. I'll soon submit a patch. :)

**Comment by mekeor** [comment]
I submitted the patch, it's being tracked here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=63987

**Comment by minad** [comment]
@mekeor Why do you need to patch jinx.el? If jinx-mod.so is available on the Emacs load path (or next to jinx.el) it should be loaded automatically without attempting compilation.

**Comment by mekeor** [comment]
@minad, thanks for the feedback. Good point. To be honest, I just replicated the logic from Guix' package [definition of `emac-vterm`](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/emacs-xyz.scm?h=44bbfc24e4bcc48d0e3343cd3d83452721af8c36#n28418), assuming it's a Guix-convention to always install .so files into `/gnu/store/.../lib`. I'll discuss with Guix community if it'd be preferred to install the `.so` file into `/gnu/store/.../share/emacs` instead.

**Comment by minad** [comment]
@mekeor 

> The maintainer of the Emacs package suggests to rather install jinx-mod.so into $out/share/emacs/site-lisp/jinx-.../ instead, i.e. right next to the .el-files

To be clear - this is not exactly what I am suggesting. Putting the shared object next to the .el file is just what happens if you use the "standard" installation method via package.el.

My suggestion is that you put the library file in some appropriate directory, which must be on the `load-path`. I assume that there exists some convention on Guix on where to install native modules. The goal is to avoid patching jinx.el. Such an approach seems to be used also by Gentoo (see #42).
