### ISSUE TITLE
Hyphens (bullet points) in Org-Mode

### ISSUE THREAD

**Issue by publicimageltd** [minad/jinx#87]
In Org-Mode, all hyphens (used as bullet points in a list) are falsely recognized as errors. The +-sign, however, or the asterisk, is not marked. Anything I can do to ignore them?

**Comment by minad** [comment]
You can use jinx-exclude-regexps.

**Comment by publicimageltd** [comment]
Thanks! Just in case someone else might also be looking for that:

```emacs-lisp
  (add-to-list 'jinx-exclude-regexps '(org-mode "[[:space:]]*-[[:space:]]*"))
```
