### ISSUE TITLE
I don't seem to get spell-checking for a few modes

### ISSUE THREAD

**Issue by anonimitoraf** [minad/jinx#88]
Thanks for this nice package. I've noticed that for js2-mode, clojure, elisp, txt and other modes spellcheck works fine but not for typescript-mode and js-mode.

* js2-mode
![Screenshot 2023-06-30 at 8 59 43 am](https://github.com/minad/jinx/assets/15933322/aeca8e43-83c7-4689-90c9-c9a414e69cdd)

* typescript-mode
![Screenshot 2023-06-30 at 8 58 55 am](https://github.com/minad/jinx/assets/15933322/41ed7c8d-d8ff-47bb-a5d2-30f19772b2b7)

I've tried disabling LSP (in case it's interfering). Is there a way I can access any logging of some sort to diagnose the issue?

My config (Doom) is simply:
```elisp
(use-package! jinx
  :hook (emacs-startup . global-jinx-mode)
  :config
  (map! :map evil-normal-state-map
    "z g" #'jinx-correct))
```

Thanks!

**Comment by minad** [comment]
Hi! Jinx works for me in the builtin `js-mode`. I suspect that some additional configuration from Doom may interfere here. 

`js-mode` is derived from `prog-mode`. Jinx uses the variable `jinx-include-faces` to only check comments and strings. You can check the faces at point with `C-u C-x =`. Maybe `font-lock-comment-face` is not present there? If that's not the cause, something else may interfere with the font locking mechanism used by Jinx. You can for example `M-x trace-function RET jinx--check-region RET`. Usually this function is executed during font locking, e.g., while editing text. 

If this also doesn't yield some clue you can copy `jinx--check-region` to the scratch buffer and add some `message` calls or debug the function. The code which checks each word (including subwords) is here:

https://github.com/minad/jinx/blob/7ebd7e3218cc427c99bf38adf3278f1ef85aa0f3/jinx.el#L421-L447

You can for example debug which words are checked and the return value of `jinx--predicates`:

~~~ elisp
(run-hook-with-args-until-success 'jinx--predicates word-start)
~~~

I hope this helps debugging the issue. If you figure something out please let me know, in particular if some changes in Jinx are needed to make it work better out of the box.

**Comment by anonimitoraf** [comment]
Thanks for all that info @minad! I'll try those out and report back

**Comment by anonimitoraf** [comment]
Cool, found it. I had to add these into `jinx-include-faces`

```elisp
    (typescript-mode tree-sitter-hl-face:comment
                     tree-sitter-hl-face:string)
    (typescript-tsx-mode web-mode-javascript-comment-face
                         web-mode-javascript-string-face)
```

**Comment by minad** [comment]
These are non-standard faces, right? Afaik the Emacs 29 treesitter support uses the normal font locking faces.

**Comment by anonimitoraf** [comment]
Ah yea I think non-standard. I haven't updated to the built-in treesitter (I'm still using https://github.com/tree-sitter/tree-sitter)
