### ISSUE TITLE
Does jinx incorporate aspell patch for improving future suggested spellings? 

### ISSUE THREAD

**Issue by gtusr** [minad/jinx#90]
From [GNU Aspell homepage](http://aspell.net/):

>patch for ispell.el for improved Aspell support also [available](https://ftp.gnu.org/gnu/aspell/ispell.el-aspell-0.1.diff). This patch will notify aspell of the replacements one makes so it can improve the suggestion list in the future. A more involved patch can be found [here](https://github.com/GNUAspell/aspell/issues/142) This one also adds UTF-8 support but will only apply cleanly to Ispell.el 3.7 beta.

**Comment by minad** [comment]
No such feature is implemented in Jinx. I am also not sure if libenchant offers an api to inform the backends about replacements. If it does, we could make use of it.
