### ISSUE TITLE
Innacurate details about jit-spell

### ISSUE THREAD

**Issue by astoff** [minad/jinx#92]
I just noticed the comparison with jit-spell in the readme, and the claim that it "highlights misspellings in the entire buffer and does not confine to just the visible text" is incorrect. Like anything relying on jit-lock (including jinx), only text near the visible part of the buffer is fontified.

**Comment by minad** [comment]
No, this is not what I mean. Jinx guarantees that only the visible region is checked, even when scrolling or when enforcing font locking, including stealth locking. In contrast jit-spell might enqueue the whole buffer for checking which has a noticeable performance impact.

**Comment by minad** [comment]
See https://github.com/minad/jinx/commit/05c172ea8509d493eb373d71c2c6fa46caee96f5 for the updated wording. I hope it makes more sense now. What do you think?

**Comment by astoff** [comment]
Makes more sense to me now, thanks!
