### ISSUE TITLE
jinx-exclude-regexps not working?

### ISSUE THREAD

**Issue by holgerschurig** [minad/jinx#94]
Hi, unfortunately Jinx tries to spell-check my C #include statements, like

```
#include "fooblebarf.h"
```

It says that foobebarf is wrong. So I tried this in my configuration:

```
  (add-to-list 'jinx-exclude-regexps '(c-mode "#include .*$"))
```

but to no avail, it still wants to spell check these include lines. Do I misunderstand the exclude regexp mechanism, because in #85 you said that one cannot exclude JavaScript imports?

My C file is indeed in c-mode, as the variable `major-mode` tells me.

**Comment by minad** [comment]
> Do I misunderstand the exclude regexp mechanism, because in https://github.com/minad/jinx/issues/85 you said that one cannot exclude JavaScript imports?

Yes. The regexp exclusion mechanism doesn't backtrack.
